import type { Metadata } from "next";
import { cn } from "@/lib/utils"; // Importing the cn utility
import {ThemeProvider} from "@/components/theme-provider"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
  {/* Google Fonts */}
  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link
    rel="preconnect"
    href="https://fonts.gstatic.com"
    crossOrigin="anonymous"
  />
  <link
    href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700;800&display=swap"
    rel="stylesheet"
  />

  {/* Tailwind CDN */}
  <script src="https://cdn.tailwindcss.com"></script>

  {/* External Tailwind config */}
</head>

      <body
        // Use the cn utility to apply the font-sans class, which now uses Plus Jakarta Sans
        className={cn("min-h-screen bg-dark-300 font-sans antialiased")}
      >
        <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
        {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
